#!/usr/bin/env node

/**
 * Setup script for SchoologyRemastered
 * Helps users configure API keys and set up the extension
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('🚀 SchoologyRemastered Setup');
  console.log('============================\n');
  
  console.log('This script will help you configure API keys for the extension.');
  console.log('API keys are optional but recommended for full functionality.\n');
  
  const geminiKey = await question('Enter your Gemini API key (or press Enter to skip): ');
  const openaiKey = await question('Enter your OpenAI API key (or press Enter to skip): ');
  
  const configContent = `// Configuration file for SchoologyRemastered
// Generated by setup script

const config = {
  // Google Gemini API Key
  // Get your key from: https://ai.google.dev/
  GEMINI_API_KEY: '${geminiKey || 'YOUR_GEMINI_API_KEY_HERE'}',
  
  // OpenAI API Key  
  // Get your key from: https://platform.openai.com/api-keys
  OPENAI_API_KEY: '${openaiKey || 'YOUR_OPENAI_API_KEY_HERE'}'
};

// Make config available globally
if (typeof window !== 'undefined') {
  window.config = config;
}`;

  try {
    fs.writeFileSync('config.js', configContent);
    console.log('\n✅ Configuration file created successfully!');
    
    if (!geminiKey && !openaiKey) {
      console.log('\n⚠️  No API keys provided. The extension will work with limited functionality:');
      console.log('   - File download and caching');
      console.log('   - Text extraction (PDF.js and OCR)');
      console.log('   - Voice commands and text-to-speech');
      console.log('   - Comment system (local storage)');
      console.log('   - Basic feedback generation (local processing)');
      console.log('\n   To enable AI features, edit config.js and add your API keys.');
    } else {
      console.log('\n🎉 Setup complete! Your API keys have been configured.');
    }
    
    console.log('\n📦 Next steps:');
    console.log('1. Install the extension in your browser:');
    console.log('   - Chrome: Go to chrome://extensions/, enable Developer mode, click "Load unpacked"');
    console.log('   - Firefox: Go to about:debugging, click "Load Temporary Add-on"');
    console.log('2. Navigate to a Schoology assignment page');
    console.log('3. Click on a file link to start using the extension');
    console.log('4. Use voice commands or click the buttons that appear');
    
  } catch (error) {
    console.error('\n❌ Error creating configuration file:', error.message);
  }
  
  rl.close();
}

setup().catch(console.error);
